### ISSUE TITLE
Deployment Error Ansible kolla-Openvswitch.yaml

### ISSUE THREAD

**Issue by r6th7g** [osism/cloud-in-a-box#109]
I tried the CiaB deployment the first time on my laptop. In the Ara UI i found out, that the Task:

Play: Apply role openvswitch
Task: openvswitch : Set system-id and hw-offload
Action: kolla_toolbox
Path: /ansible/roles/openvswitch/tasks/post-config.yml:3
Host: manager.systems.in-a-box.cloud
Status: failed
Started: 22 Jul 2023 13:04:52 +0000
Ended: 22 Jul 2023 13:04:52 +0000
Duration: 00:00:00.54
Tags:
openvswitch

Gave this Message twice:
kolla_toolbox container is not running.

The seven predecessor tasks ran without an error.

There are 14 tasks in total which did not work. But i think it is better to go step by step through this...

Thanks for your support.

**Comment by rhm681** [comment]
is there a way to force the deployment again without having to rebuild the whole system?

**Comment by rhm681** [comment]
I'm trying a second time and the first error during the deployment is: "kolla_toolbox container is not running" - again.

**Comment by berendt** [comment]
Normally, the deployment runs completely without errors after the 2nd boot. I think it would be better to run a new deployment before we start debugging. Since some of the images don't seem to be available, there were probably problems with the download there.

Kibana was replaced with Opensearch Dashboards.

**Comment by rhm681** [comment]
Hi Christian,
there is no further investigation necessary. The 4th attempt on my second laptop was successfull, obviously. Really great!
I am writing a Blog post about this and will inform you, when I'm fine with that.
Thanks and regards,
Robert

**Comment by berendt** [comment]
Thanks for the feedback. We will have to work on resilience when deploying in one piece in the future.
