### ISSUE TITLE
Detect second NIC

### ISSUE THREAD

**Issue by garloff** [osism/cloud-in-a-box#15]
It would be good to indeed use the 2nd NIC for the provider network on the CiaB as designed.

**Comment by garloff** [comment]
Code to find the 2nd NIC:
```
firstip_address=$(hostname --all-ip-addresses | awk '{print $1}')
first_network_interface=$(ip -br -4 a sh | grep ${firstip_address} | awk '{print $1}')
second_network_interface=$(cat /proc/net/dev | grep "^${first_network_interface:0:3}" | grep -v "${first_network_interface}" | sort | head -n1| sed 's/:.*$//')
```
This assumes the 2nd NIC's name starts with the same 3 letters. If multiple exist, the alpahbetically first one is taken. If none exists, second_network_interface will be empty.

**Comment by garloff** [comment]
Sidenote: I always detect the *primary* IP address as the one that has the default route.
`first_network_interface=$(ip route show | grep ^default | head -n1 | sed 's/^.*dev \([^ ]*\) .*/\1/')`
This tends to reasonable robust ...

**Comment by garloff** [comment]
Would still be good to detect the 2nd NIC and offer ways to use it.
That said, the current CiaB installs work just fine with just one NIC and there is a `public` net that allows outgoing and incoming traffic to VMs.
So feel free to disreagard this one as a nice-to-have.

**Comment by berendt** [comment]
Replaced by #106.

I think it makes more sense to document this as an additional step.
