### ISSUE TITLE
issue has hardcoded IP address

### ISSUE THREAD

**Issue by garloff** [osism/cloud-in-a-box#16]
The install automation writes the IP address to the /etc/issue file which is a nice convenience.
However, if the IP address changes after the install, it's no longer true.

**Comment by garloff** [comment]
Here's a a better `/etc/issue`:
```
Ubuntu 22.04 LTS
\l on \n.\O (\s \m \r)
\U \d \t
\4 \6
```

**Comment by berendt** [comment]
The /etc/issue is only used to output the IP address assigned via DHCP in the first step after installation. In the further process, /etc/issue is no longer needed and should actually be replaced by osism.commons.motd.
