### ISSUE TITLE
Bug: add_status does not exist

### ISSUE THREAD

**Issue by garloff** [osism/cloud-in-a-box#181]
In a CiaB deployment (2023-11-18/19); the `/opt/cloud-in-a-box/deploy.sh sandbox` errors out in the last line due to `add_status` not being a known command. I guess this should be a shell function, pulled in via include.sh, but I can't see it.
Consequently, the `deploy.sh` isn't called, resulting in a very incomplete installation.
(But fortunately one that can easily be completed manually by calling `deploy.sh sandbox`.`

**Comment by scoopex** [comment]
Yes, it seems that we lost this function of the initial implementation in the merge process :-(
