### ISSUE TITLE
add proper dns entries

### ISSUE THREAD

**Issue by tibeer** [osism/cloud-in-a-box#19]
currently, horizon is only available via https://api.in-a-box.cloud/ which is not intuitive.
Same goes for:
Grafana
Kibana
Netdata
RabbitMQ

**Comment by berendt** [comment]
Grafana, Kibana, Netdata and RabbitMQ need more work than simply adding an additional DNS entry. This will be done in the future, independent of this issue.

I will add dashboard.in-a-box.cloud as DNS entry for Horizon.

**Comment by berendt** [comment]
dashboard.in-a-box.cloud is already there. Please check and document.

**Comment by berendt** [comment]
Further services tracked in https://github.com/osism/issues/issues/390.
