### ISSUE TITLE
Horizon: Access to instances "Log" and "Console" tabs is not working

### ISSUE THREAD

**Issue by tibeer** [osism/cloud-in-a-box#20]
If you create an instance within Horizon, you cannot view details of it within the tabs "Log" and "Console". If you want to pop out the Console, it would like to redirect to: http://192.168.16.254:6080/vnc_auto.html?path=%3Ftoken%XXXXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX&title=test(XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX)

**Comment by berendt** [comment]
I installed a CiaB yesterday and both the console and the log worked there.
