### ISSUE TITLE
CiaB: Document flavor creation

### ISSUE THREAD

**Issue by garloff** [osism/cloud-in-a-box#22]
The CiaB OpenStack comes without any flavors.
Unless we want to have the flavor-manager create a somewhat complete set of SCS flavors, we should document how to get some flavors registered in our quick start guide:
```
openstack --os-cloud=ciab-admin flavor create --disk 5 --vcpus 1 --ram 1024 --property hw_rng:allowed='True' SCS-1L:1:5
```
Oh, we might need to document how to get the `clouds.yaml` and rename the cloud name from openstack to ciab-admin and create the machting `secure.yaml`

**Comment by ra-beer** [comment]
We will document this in the Testbed documentation and add a link to the Quickstart.
https://github.com/osism/testbed/issues/1433
