### ISSUE TITLE
CiaB: Create an image

### ISSUE THREAD

**Issue by garloff** [osism/cloud-in-a-box#23]
The CiaB comes without an image.
So add instructions how to create one:
* Download https://cloud-images.ubuntu.com/jammy/current/jammy-server-cloudimg-amd64.img
* `openstack image create --disk-format qcow2 --min-disk 3 --min-ram 512 --file "jammy-server-cloudimg-amd64.img" --property image_build_date="2022-12-19" --property image_original_user="ubuntu" --property architecture="x86_64" --property os_distro="Ubuntu" --property os_version="22.04" --property hw_disk_bus=scsi --property hw_scsi_model=virtio-scsi --property hw_rng_model=virtio --property hw_vif_multiqueue_enabled=true --property image_source="https://kfg.images.obs-website.eu-de.otc.t-systems.com/jammy-server-cloudimg-amd64.img" --property image_description=https://kfg.images.obs-website.eu-de.otc.t-systems.com/ --property replace_frequency=never --property provided_until=2023-12-19 --property uuid_validity=2023-12-19 --tag managed_by_$LOGNAME --tag os:ubuntu --tag path:os:linux:ubuntu  --property hw_qemu_guest_agent="yes" "Ubuntu 22.04"` (replacing the dates to reflect reality)
* Image registration script `imgreg.sh` (which created the command line above) and openSUSE images at https://kfg.images.obs-website.eu-de.otc.t-systems.com/

**Comment by ra-beer** [comment]
As decided we will document this in the Testbed documentation and link this to CiaB.
https://github.com/osism/testbed/issues/1432
