### ISSUE TITLE
Document how to use Cloud in a Box on a VMware ESXi 7.0 host

### ISSUE THREAD

**Issue by berendt** [osism/cloud-in-a-box#299]
* https://osism.tech/docs/guides/other-guides/cloud-in-a-box

**Comment by snowmaster007** [comment]
As requested the missing docs have been added.

Please find below the appropriate pull request:
https://github.com/osism/osism.github.io/pull/661

**Comment by berendt** [comment]
@snowmaster007 Merged the specs. Please add some more details how to create the VM. UEFI, ...
