### ISSUE TITLE
CiaB: noVNC address incorrect

### ISSUE THREAD

**Issue by garloff** [osism/cloud-in-a-box#37]
When trying to access the noVNC console of started VMs, the OpenStack dashboard (horizon) fails to work.
http://192.168.16.254:6080/vnc_auto.html?path=%253Ftoken%253D....
gives me "Connection reset".
The same non-working URL is also reported by `openstack console url show`.
Checking the qemu command line, I tried the same URL with 192.168.16.10 instead of .254 to make it work.
This fortunately succeeded.

**Comment by berendt** [comment]
Do you have the latest version? The current novnc address is set to https://api.in-a-box.cloud:6080/vnc_lite.html.

**Comment by garloff** [comment]
This was an installation from the end of Dec. I can retry with a current installation.

**Comment by berendt** [comment]
Try this. I installed a CiaB yesterday and both the console and the log worked there.

**Comment by garloff** [comment]
It works on a fresh install.
THANKS!
