### ISSUE TITLE
CiaB: How to trust the CA

### ISSUE THREAD

**Issue by garloff** [osism/cloud-in-a-box#43]
In my CiaB installation, I had to use --insecure for API and add exceptions for browser access.
The connections are all secured with TLS, which is good, and the certs are all signed by the OSISM CiaB CA.
I would have imported the CA to trust it, but a quick search did not allow me to find it.
Some documentation would be welcome!
(I may not have searched long enough, maybe the docs exist. Note also that this was a deployment from the end of Dec, things might have changed since.)

**Comment by berendt** [comment]
It's now documented as a part of the OSISM testbed documentation.
