### ISSUE TITLE
Image not added

### ISSUE THREAD

**Issue by tibeer** [osism/cloud-in-a-box#52]
Commit https://github.com/osism/cloud-in-a-box/commit/2f90b487964bc44746baf514c62f944d63717703 introduced a functionality to preload the installation with a Cirros image. The command is not functional yet because of an old version of python-osism. This will automatically be resolved, once there is a new release (https://github.com/osism/release) with a newer version of python-osism (https://github.com/osism/python-osism)

**Comment by berendt** [comment]
Please have a look at https://github.com/osism/testbed/blob/main/scripts/deploy/300-openstack-services-basic.sh#L23-L30 and use the same workaround here.
