### ISSUE TITLE
External network connectivity not working

### ISSUE THREAD

**Issue by berendt** [osism/cloud-in-a-box#59]

**Comment by berendt** [comment]
After a lot of trial and error, I seem to have found a solution that works stably.

**Comment by berendt** [comment]
Also added wireguard access with ee01e3f1590e9a03e141d64daf5d1cce7570dfa7. Floating IP address can now be accessed.

**Comment by berendt** [comment]
Running a few more test deployments tomorrow. Can be closed then.

**Comment by berendt** [comment]
@ra-beer Please re-deploy your local CiaB system and test if instances can reach the external network and test if you can access instances via the Wireguard tunnel from a local workstation.

**Comment by ra-beer** [comment]
Seems to work fine. Can we close this?

**Comment by garloff** [comment]
Works nicely for me as well.
Thanks!
