### ISSUE TITLE
Can all required software be put in the usb image to avoid downloading?

### ISSUE THREAD

**Issue by neuroserve** [osism/cloud-in-a-box#74]
It would be nice, if the installation could work without an internet connection. USB-Sticks with much more capacity are widely available. Thus it would be nice to know, how much capacity would be needed to put all required software (container images, etc.) already on the USB stick to avoid downloading them from the internet.

I'm not too familiar with the installation process of cloud-in-a-box but maybe there is some inspiration in  https://github.com/TritonDataCenter/triton/blob/master/docs/developer-guide/coal-setup.md
Docs about building the coal image can be found in https://github.com/TritonDataCenter/sdc-headnode/blob/master/README.md.

**Comment by berendt** [comment]
This has not been thought of so far. But we can implement this. Take this into the next SCS refinement.

**Comment by berendt** [comment]
The node-image becomes too large (> 20 GByte) because the layering function cannot be used since each image is only provided as a blob.
