### ISSUE TITLE
Add single node Ceph deployment

### ISSUE THREAD

**Issue by berendt** [osism/cloud-in-a-box#9]

**Comment by berendt** [comment]
Discuss this in more detail in the next SCS meeting.

**Comment by fkr** [comment]
Can we add some more content to this issue? As in, what is the DoD of this and what is the expected outcome of it.

**Comment by berendt** [comment]
As a developer or integrator of SCS, I want to be able to test the technology as well as possible on a single node. These include Ceph RGW and Ceph RBD in particular. Therefore, it is necessary to run a Ceph installation on the single node as well, since we use Ceph as the standard storage backend everywhere.

The task is done when Cinder, Nova + Glance can work with Ceph as storage backend and S3 and Swift are usable via Ceph RGW.

- [ ] Cinder / Ceph
- [ ] Glance / Ceph
- [ ] Nova / Ceph
- [ ] Swift endpoint is there
- [ ] S3 is usable via Ceph RGW
